create database yourname;
use yourname;

CREATE TABLE DRUG (
    DRUGBANK_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(512) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    CAS_NUMBER VARCHAR(50)
);


CREATE TABLE CLASSIFICATION (
    DRUGBANK_ID VARCHAR(20) PRIMARY KEY,
    KINGDOM VARCHAR(256),
    SUPERCLASS VARCHAR(256),
    CLASS VARCHAR(256),
    SUBCLASS VARCHAR(256),
    FOREIGN KEY (DRUGBANK_ID) REFERENCES DRUG(DRUGBANK_ID) ON DELETE CASCADE
);

DELIMITER //
-- INSERT 트리거
CREATE TRIGGER set_null_for_classification_insert
BEFORE INSERT ON CLASSIFICATION
FOR EACH ROW
BEGIN
    IF NEW.KINGDOM IS NULL THEN
        SET NEW.SUPERCLASS = NULL;
        SET NEW.CLASS = NULL;
        SET NEW.SUBCLASS = NULL;
    ELSEIF NEW.SUPERCLASS IS NULL THEN
        SET NEW.CLASS = NULL;
        SET NEW.SUBCLASS = NULL;
    ELSEIF NEW.CLASS IS NULL THEN
        SET NEW.SUBCLASS = NULL;
    END IF;
END //
-- UPDATE 트리거
CREATE TRIGGER set_null_for_classification_update
BEFORE UPDATE ON CLASSIFICATION
FOR EACH ROW
BEGIN
    IF NEW.KINGDOM IS NULL THEN
        SET NEW.SUPERCLASS = NULL;
        SET NEW.CLASS = NULL;
        SET NEW.SUBCLASS = NULL;
    ELSEIF NEW.SUPERCLASS IS NULL THEN
        SET NEW.CLASS = NULL;
        SET NEW.SUBCLASS = NULL;
    ELSEIF NEW.CLASS IS NULL THEN
        SET NEW.SUBCLASS = NULL;
    END IF;
END //
DELIMITER ;

CREATE TABLE TARGET (
    TARGET_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL UNIQUE,
    ORGANISM VARCHAR(256)
);

CREATE TABLE ENZYME (
    ENZYME_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL UNIQUE,
    ORGANISM VARCHAR(256)
);

CREATE TABLE PATHWAY (
    SMPDB_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL UNIQUE,
    CATEGORY VARCHAR(256)
);

CREATE TABLE DRUG_ENZYME_ACTION (
    DRUGBANK_ID VARCHAR(20),
    ENZYME_ID VARCHAR(20),
    ENZYME_ACTION VARCHAR(256),
    PRIMARY KEY (DRUGBANK_ID, ENZYME_ID),
    FOREIGN KEY (DRUGBANK_ID) REFERENCES DRUG(DRUGBANK_ID) ON DELETE CASCADE,
    FOREIGN KEY (ENZYME_ID) REFERENCES ENZYME(ENZYME_ID) ON DELETE CASCADE
);

CREATE TABLE DRUG_PATH_ASSOCIATION (
    DRUGBANK_ID VARCHAR(20),
    SMPDB_ID VARCHAR(20),
    UNIPROT_ID VARCHAR(20),
    PRIMARY KEY (DRUGBANK_ID, SMPDB_ID, UNIPROT_ID),
    FOREIGN KEY (DRUGBANK_ID) REFERENCES DRUG(DRUGBANK_ID) ON DELETE CASCADE,
    FOREIGN KEY (SMPDB_ID) REFERENCES PATHWAY(SMPDB_ID) ON DELETE CASCADE
);

CREATE TABLE DRUG_TARGET (
    DRUGBANK_ID VARCHAR(20),
    TARGET_ID VARCHAR(20),
    PRIMARY KEY (DRUGBANK_ID, TARGET_ID),
    FOREIGN KEY (DRUGBANK_ID) REFERENCES DRUG(DRUGBANK_ID) ON DELETE CASCADE,
    FOREIGN KEY (TARGET_ID) REFERENCES TARGET(TARGET_ID) ON DELETE CASCADE
);
